### PR TITLE
Removes the old Fontawesome library and replaces the Twitter link in the footer with a link to Mastodon

### PR DESCRIPTION
**Pull request by froschdesign**

### CODE REVIEW

**Comment by Xerkus** [comment]
migration docs say `fa` needs to be changed to `fa-solid` https://fontawesome.com/docs/web/setup/upgrade/upgrade-from-v4

**Comment by froschdesign** [comment]
I have added version 5 here because this version still provides the icons via CDN and contains the Mastodon icon. Version 6 requires a kit or must be downloaded.

**Comment by Xerkus** [comment]
I see. Is there a reason download route not taken here?

**Comment by froschdesign** [comment]
The decision has already been made in the past. Please see `default.phtml`.
Personally, I just wanted a quick fix for the problem and not an expansion of the build process with Gulp.

**Comment by Xerkus** [comment]
Ok. Thank you.

**Comment by froschdesign** [comment]
@Xerkus 
Your questions are entirely justified. After all, I omitted this information when I opened the pull request.
Thanks for your review and help!

**Pull request merged**
